# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GifShow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GifShow
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~>  4.2'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  target 'GifShowTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end

  target 'GifShowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
